# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uncensored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='has_mask',
            field=models.CharField(default='y', max_length=2, null=True),
        ),
    ]
