# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0002_auto_20170716_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='uncensored',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
