# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_actors_uncensored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gid',
            field=models.CharField(max_length=255),
        ),
    ]
