# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_auto_20170716_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='file_name',
            field=models.CharField(max_length=1023),
        ),
    ]
