# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_auto_20170716_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnet',
            name='hd',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
